apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-{{ .Release.Namespace }}
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http