apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.sever }}
      path: {{ .Values.vault.vaultPath }}
      version: "v2"
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.auth.kubernetes.mountPath }}
          role: {{ .Values.vault.auth.kubernetes.role }}
          serviceAccountRef:
            name: {{ .Values.vault.auth.kubernetes.serviceAccountName }}