name: example-secret
namespace: dev
refreshInterval: 1h

secretStore:
  name: vault-store
  kind: SecretStore

target:
  creationPolicy: Owner

data:
  - secretKey: username
    remoteRef:
      key: example
      property: username
  - secretKey: password
    remoteRef:
      key: example
      property: password